-- -------------------------------------------------------------------------
-- 001 — Outlets, SOP categories, templates and assignments
--
-- GENERATED by scripts/generate_sop_seed.py — do not hand-edit.
--
-- The mapping approved on 26 Aug 2026: AKIRA's two real operational
-- checklists, the mise-en-place par sheet as numeric prep checks, and one
-- Food Safety Daily template covering temperature logging the paper lacks.
--
--   14 templates, 57 items
--   18 require a photo, 11 critical, 23 take a value
--
-- Photo and critical flags are a STARTING POINT. Admins edit them through
-- the template builder; migration 0011 keeps those edits from reaching
-- backwards into completed runs.
--
-- Users are NOT seeded here: profiles.id references auth.users, which
-- Supabase Auth owns. See scripts/seed_users.py.
--
-- Idempotent: re-running updates labels and adds nothing twice.
-- -------------------------------------------------------------------------

insert into outlets (code, name, city, geo_lat, geo_lng, opened_on) values
    ('AKR-NT01', 'AKIRA New Town', 'Kolkata', 22.5023, 88.3852, '2026-07-17'::date),
    ('AKR-DEV02', 'Dev Outlet 2', 'Kolkata', 22.5726, 88.3639, null::date)
on conflict (code) do update set
    name = excluded.name,
    city = excluded.city,
    geo_lat = excluded.geo_lat,
    geo_lng = excluded.geo_lng;

insert into sop_categories (key, label, label_bn, sort_order, icon) values
    ('opening', 'Opening', 'খোলা', 10, 'sunrise'),
    ('closing', 'Closing', 'বন্ধ', 20, 'moon'),
    ('cleaning', 'Cleaning', 'পরিষ্কার', 30, 'spray-can'),
    ('food_safety', 'Food Safety', 'খাদ্য নিরাপত্তা', 40, 'thermometer'),
    ('maintenance', 'Maintenance', 'রক্ষণাবেক্ষণ', 50, 'wrench'),
    ('inventory', 'Inventory', 'মজুদ', 60, 'package')
on conflict (key) do update set
    label = excluded.label,
    label_bn = excluded.label_bn,
    sort_order = excluded.sort_order,
    icon = excluded.icon;

-- ======================================================================
-- Kitchen Cleaning — Daily  (4 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Kitchen Cleaning — Daily' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Kitchen Cleaning — Daily', 'দৈনিক রান্নাঘর পরিষ্কার', 'Section A of the Kitchen Cleaning & Sanitation sheet.',
               'daily'::frequency, 'closing'::day_part, 1
          from sop_categories c where c.key = 'cleaning'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Daily working range cleaning', 'দৈনিক কর্মক্ষেত্র পরিষ্কার করা',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Daily working range cleaning', 'দৈনিক কর্মক্ষেত্র পরিষ্কার করা',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 2, 'Daily working station cleaning', 'প্রতিদিন কর্মস্থল পরিষ্কার করা',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 2, 'Daily working station cleaning', 'প্রতিদিন কর্মস্থল পরিষ্কার করা',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 3, 'Daily trolley cleaning', 'প্রতিদিন ট্রলি পরিষ্কার করা',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 3, 'Daily trolley cleaning', 'প্রতিদিন ট্রলি পরিষ্কার করা',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 4, 'Daily floor cleaning', 'প্রতিদিন মেঝে পরিষ্কার করা',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 4, 'Daily floor cleaning', 'প্রতিদিন মেঝে পরিষ্কার করা',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'shift_lead'::user_role,
                    '{0,1,2,3,4,5,6}',
                    null,
                    null,
                    '00:30'::time, 30);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Kitchen Cleaning — Alternate Day  (4 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Kitchen Cleaning — Alternate Day' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Kitchen Cleaning — Alternate Day', 'একদিন অন্তর রান্নাঘর পরিষ্কার', 'Section B of the Kitchen Cleaning & Sanitation sheet.',
               'alternate_day'::frequency, 'closing'::day_part, 1
          from sop_categories c where c.key = 'cleaning'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Equipment area dusting', 'সরঞ্জাম এলাকা ধুলো পরিষ্কার করা',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Equipment area dusting', 'সরঞ্জাম এলাকা ধুলো পরিষ্কার করা',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 2, 'Cobweb cleaning', 'মাকড়সার জাল পরিষ্কার করা',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 2, 'Cobweb cleaning', 'মাকড়সার জাল পরিষ্কার করা',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 3, 'Refrigerator outer body clean', 'রেফ্রিজারেটরের বাইরের অংশ পরিষ্কার',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 3, 'Refrigerator outer body clean', 'রেফ্রিজারেটরের বাইরের অংশ পরিষ্কার',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 4, 'Back corridor brooming', 'পিছনের করিডোর ঝাড়ু দেওয়া',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 4, 'Back corridor brooming', 'পিছনের করিডোর ঝাড়ু দেওয়া',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'shift_lead'::user_role,
                    '{0,1,2,3,4,5,6}',
                    2,
                    current_date,
                    '00:30'::time, 30);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Deep Clean — Non-veg Fridge (Mon)  (1 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Deep Clean — Non-veg Fridge (Mon)' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Deep Clean — Non-veg Fridge (Mon)', 'গভীর পরিষ্কার — আমিষ ফ্রিজ (সোম)', 'Monday slot of the weekly deep-clean rota.',
               'weekly'::frequency, 'closing'::day_part, 1
          from sop_categories c where c.key = 'cleaning'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Non-veg fridge clean & deep clean at night', 'রাতে আমিষ ফ্রিজ পরিষ্কার ও ভালোভাবে পরিষ্কার করুন',
                true, false,
                null::value_type, null, null, null,
                true, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Non-veg fridge clean & deep clean at night', 'রাতে আমিষ ফ্রিজ পরিষ্কার ও ভালোভাবে পরিষ্কার করুন',
                true, false,
                null::value_type, null, null, null,
                true, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'shift_lead'::user_role,
                    array[1],
                    null,
                    null,
                    '00:30'::time, 60);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Deep Clean — Veg Chiller (Tue)  (1 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Deep Clean — Veg Chiller (Tue)' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Deep Clean — Veg Chiller (Tue)', 'গভীর পরিষ্কার — ভেজিটেবল চিলার (মঙ্গল)', 'Tuesday slot of the weekly deep-clean rota.',
               'weekly'::frequency, 'closing'::day_part, 1
          from sop_categories c where c.key = 'cleaning'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Veg chiller clean', 'ভেজিটেবল চিলার পরিষ্কার',
                true, false,
                null::value_type, null, null, null,
                true, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Veg chiller clean', 'ভেজিটেবল চিলার পরিষ্কার',
                true, false,
                null::value_type, null, null, null,
                true, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'shift_lead'::user_role,
                    array[2],
                    null,
                    null,
                    '00:30'::time, 60);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Deep Clean — Veg Freezer (Wed)  (1 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Deep Clean — Veg Freezer (Wed)' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Deep Clean — Veg Freezer (Wed)', 'গভীর পরিষ্কার — সবজি ফ্রিজার (বুধ)', 'Wednesday slot of the weekly deep-clean rota.',
               'weekly'::frequency, 'closing'::day_part, 1
          from sop_categories c where c.key = 'cleaning'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Veg freezer clean', 'সবজি ফ্রিজার পরিষ্কার',
                true, false,
                null::value_type, null, null, null,
                true, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Veg freezer clean', 'সবজি ফ্রিজার পরিষ্কার',
                true, false,
                null::value_type, null, null, null,
                true, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'shift_lead'::user_role,
                    array[3],
                    null,
                    null,
                    '00:30'::time, 60);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Deep Clean — Staff Toilet (Thu)  (1 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Deep Clean — Staff Toilet (Thu)' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Deep Clean — Staff Toilet (Thu)', 'গভীর পরিষ্কার — কর্মচারীদের শৌচাগার (বৃহস্পতি)', 'Thursday slot of the weekly deep-clean rota.',
               'weekly'::frequency, 'closing'::day_part, 1
          from sop_categories c where c.key = 'cleaning'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Staff toilet clean', 'কর্মচারীদের শৌচাগার পরিষ্কার',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Staff toilet clean', 'কর্মচারীদের শৌচাগার পরিষ্কার',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'shift_lead'::user_role,
                    array[4],
                    null,
                    null,
                    '00:30'::time, 60);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Maintenance Clean (Fri & Sat)  (1 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Maintenance Clean (Fri & Sat)' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Maintenance Clean (Fri & Sat)', 'রক্ষণাবেক্ষণমূলক পরিষ্কার (শুক্র ও শনি)', 'Friday and Saturday slots. Maintenance only, explicitly not a deep clean.',
               'weekly'::frequency, 'closing'::day_part, 1
          from sop_categories c where c.key = 'cleaning'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Maintenance clean (no deep clean)', 'রক্ষণাবেক্ষণমূলক পরিষ্কার (গভীরভাবে পরিষ্কার নয়)',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Maintenance clean (no deep clean)', 'রক্ষণাবেক্ষণমূলক পরিষ্কার (গভীরভাবে পরিষ্কার নয়)',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'shift_lead'::user_role,
                    array[5, 6],
                    null,
                    null,
                    '00:30'::time, 60);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Floor & Dining — Daily  (10 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Floor & Dining — Daily' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Floor & Dining — Daily', 'দৈনিক ফ্লোর ও ডাইনিং', 'Dining-floor half of the Service & Housekeeping daily sheet.',
               'daily'::frequency, 'opening'::day_part, 1
          from sop_categories c where c.key = 'opening'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Chair / stool wiped', 'চেয়ার / টুল মোছা হয়েছে',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Chair / stool wiped', 'চেয়ার / টুল মোছা হয়েছে',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 2, 'Cutlery wiped and set up', 'ছুরি-চামচ মুছে সাজিয়ে রাখা হয়েছে',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 2, 'Cutlery wiped and set up', 'ছুরি-চামচ মুছে সাজিয়ে রাখা হয়েছে',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 3, 'Floor dusted, wet mopped, dry mopped', 'মেঝে ঝাড়া + ভেজা মোছা + শুকনো মোছা',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 3, 'Floor dusted, wet mopped, dry mopped', 'মেঝে ঝাড়া + ভেজা মোছা + শুকনো মোছা',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 4, 'Glass water bottles cleaned', 'কাচের জলের বোতল পরিষ্কার করা হয়েছে',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 4, 'Glass water bottles cleaned', 'কাচের জলের বোতল পরিষ্কার করা হয়েছে',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 5, 'Library rack dusted', 'লাইব্রেরি র‍্যাকের ধুলো ঝাড়া',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 5, 'Library rack dusted', 'লাইব্রেরি র‍্যাকের ধুলো ঝাড়া',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 6, 'Napkins folded', 'ভাঁজ করা ন্যাপকিন (সর্বনিম্ন ২ প্যাকেট)',
                false, true,
                'number'::value_type, 2, null, 'packets',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 6, 'Napkins folded', 'ভাঁজ করা ন্যাপকিন (সর্বনিম্ন ২ প্যাকেট)',
                false, true,
                'number'::value_type, 2, null, 'packets',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 7, 'Room freshener checked', 'রুম ফ্রেশনার চেক',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 7, 'Room freshener checked', 'রুম ফ্রেশনার চেক',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 8, 'Window panes and glass door cleaned, both sides', 'জানালার কাচ ও কাচের দরজা (উভয় পাশ) পরিষ্কার করা হয়েছে',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 8, 'Window panes and glass door cleaned, both sides', 'জানালার কাচ ও কাচের দরজা (উভয় পাশ) পরিষ্কার করা হয়েছে',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 9, 'Mirror clean', 'আয়নার মতো পরিষ্কার',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 9, 'Mirror clean', 'আয়নার মতো পরিষ্কার',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 10, 'Cobweb check', 'মাকড়সার জাল পরীক্ষা',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 10, 'Cobweb check', 'মাকড়সার জাল পরীক্ষা',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'staff'::user_role,
                    '{0,1,2,3,4,5,6}',
                    null,
                    null,
                    '17:00'::time, 30);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Washroom & Waste — Daily  (6 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Washroom & Waste — Daily' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Washroom & Waste — Daily', 'দৈনিক শৌচাগার ও বর্জ্য', 'Washroom half of the Service & Housekeeping daily sheet.',
               'daily'::frequency, 'closing'::day_part, 1
          from sop_categories c where c.key = 'closing'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Dustbin cleaning', 'ময়লার ঝুড়ি পরিষ্কার',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Dustbin cleaning', 'ময়লার ঝুড়ি পরিষ্কার',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 2, 'Soap dispenser refill', 'সাবান ডিসপেনসার রিফিল',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 2, 'Soap dispenser refill', 'সাবান ডিসপেনসার রিফিল',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 3, 'WC clean', 'ডব্লিউসি (WC) পরিষ্কার',
                true, false,
                null::value_type, null, null, null,
                true, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 3, 'WC clean', 'ডব্লিউসি (WC) পরিষ্কার',
                true, false,
                null::value_type, null, null, null,
                true, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 4, 'Sink clean', 'সিঙ্ক পরিষ্কার',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 4, 'Sink clean', 'সিঙ্ক পরিষ্কার',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 5, 'Mirror clean', 'আয়না পরিষ্কার',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 5, 'Mirror clean', 'আয়না পরিষ্কার',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 6, 'Wall wiped with wet duster', 'ভেজা ডাস্টার দিয়ে দেয়াল মোছা',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 6, 'Wall wiped with wet duster', 'ভেজা ডাস্টার দিয়ে দেয়াল মোছা',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'staff'::user_role,
                    '{0,1,2,3,4,5,6}',
                    null,
                    null,
                    '00:30'::time, 30);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Dining Deep Clean  (2 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Dining Deep Clean' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Dining Deep Clean', 'ডাইনিং গভীর পরিষ্কার', 'Section B periodic tasks. Days assumed Mon/Wed/Fri — the sheet does not name them.',
               'weekly'::frequency, 'closing'::day_part, 1
          from sop_categories c where c.key = 'cleaning'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Dining area scrubbed wall to wall', 'খাবার ঘরের দেয়াল থেকে দেয়াল পর্যন্ত ঘষেমেজে পরিষ্কার করা',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Dining area scrubbed wall to wall', 'খাবার ঘরের দেয়াল থেকে দেয়াল পর্যন্ত ঘষেমেজে পরিষ্কার করা',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 2, 'Figure dusting', 'মূর্তি ধুলো',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 2, 'Figure dusting', 'মূর্তি ধুলো',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'staff'::user_role,
                    array[1, 3, 5],
                    null,
                    null,
                    '00:30'::time, 60);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Fortnightly Maintenance  (2 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Fortnightly Maintenance' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Fortnightly Maintenance', 'পাক্ষিক রক্ষণাবেক্ষণ', 'Section B every-15-days tasks.',
               'fortnightly'::frequency, 'mid'::day_part, 1
          from sop_categories c where c.key = 'maintenance'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'AC filter clean', 'এসি ফিল্টার পরিষ্কার',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'AC filter clean', 'এসি ফিল্টার পরিষ্কার',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 2, 'Screw tightening & table maintenance', 'স্ক্রু টাইট করা এবং টেবিলের রক্ষণাবেক্ষণ',
                false, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 2, 'Screw tightening & table maintenance', 'স্ক্রু টাইট করা এবং টেবিলের রক্ষণাবেক্ষণ',
                false, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'outlet_manager'::user_role,
                    '{0,1,2,3,4,5,6}',
                    14,
                    current_date,
                    '15:00'::time, 120);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Kitchen Prep Readiness  (14 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Kitchen Prep Readiness' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Kitchen Prep Readiness', 'রান্নাঘর প্রস্তুতি', 'Section A of the Mise-en-place sheet. Minimums are the printed par levels.',
               'daily'::frequency, 'opening'::day_part, 1
          from sop_categories c where c.key = 'inventory'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Noodles', 'নুডলস',
                false, true,
                'number'::value_type, 30, null, 'portions cut',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Noodles', 'নুডলস',
                false, true,
                'number'::value_type, 30, null, 'portions cut',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 2, 'Yakitori — Pork', 'ইয়াকিতোরি - শুকরের মাংস',
                false, true,
                'number'::value_type, 2, null, 'boxes',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 2, 'Yakitori — Pork', 'ইয়াকিতোরি - শুকরের মাংস',
                false, true,
                'number'::value_type, 2, null, 'boxes',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 3, 'Yakitori — Chicken', 'ইয়াকিতোরি - চিকেন',
                false, true,
                'number'::value_type, 3, null, 'boxes',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 3, 'Yakitori — Chicken', 'ইয়াকিতোরি - চিকেন',
                false, true,
                'number'::value_type, 3, null, 'boxes',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 4, 'Yakitori — Prawn', 'ইয়াকিতোরি - চিংড়ি',
                false, true,
                'number'::value_type, 3, null, 'kg',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 4, 'Yakitori — Prawn', 'ইয়াকিতোরি - চিংড়ি',
                false, true,
                'number'::value_type, 3, null, 'kg',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 5, 'Mushroom', 'মাশরুম',
                false, true,
                'number'::value_type, 10, null, 'packs',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 5, 'Mushroom', 'মাশরুম',
                false, true,
                'number'::value_type, 10, null, 'packs',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 6, 'Ajitama (ramen eggs)', 'আজিতামা (রামেন ডিম)',
                false, true,
                'number'::value_type, 30, null, 'pcs',
                true, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 6, 'Ajitama (ramen eggs)', 'আজিতামা (রামেন ডিম)',
                false, true,
                'number'::value_type, 30, null, 'pcs',
                true, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 7, 'Karaage', 'কারাগে',
                false, true,
                'number'::value_type, 2, null, 'kg marinated',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 7, 'Karaage', 'কারাগে',
                false, true,
                'number'::value_type, 2, null, 'kg marinated',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 8, 'Gyoza — Chicken', 'গিয়োজা - চিকেন',
                false, true,
                'number'::value_type, 50, null, 'pcs',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 8, 'Gyoza — Chicken', 'গিয়োজা - চিকেন',
                false, true,
                'number'::value_type, 50, null, 'pcs',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 9, 'Gyoza — Pork', 'গিয়োজা - শূকরের মাংস',
                false, true,
                'number'::value_type, 50, null, 'pcs',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 9, 'Gyoza — Pork', 'গিয়োজা - শূকরের মাংস',
                false, true,
                'number'::value_type, 50, null, 'pcs',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 10, 'Gyoza — Mushroom', 'গিয়োজা - মাশরুম',
                false, true,
                'number'::value_type, 50, null, 'pcs',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 10, 'Gyoza — Mushroom', 'গিয়োজা - মাশরুম',
                false, true,
                'number'::value_type, 50, null, 'pcs',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 11, 'Pickled bok choy', 'আচারযুক্ত বক চয়',
                false, true,
                'number'::value_type, 400, null, 'g',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 11, 'Pickled bok choy', 'আচারযুক্ত বক চয়',
                false, true,
                'number'::value_type, 400, null, 'g',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 12, 'Pickled mushroom', 'আচারযুক্ত মাশরুম',
                false, true,
                'number'::value_type, 400, null, 'g',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 12, 'Pickled mushroom', 'আচারযুক্ত মাশরুম',
                false, true,
                'number'::value_type, 400, null, 'g',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 13, 'Spring onion, cut', 'পেঁয়াজ পাতা',
                false, true,
                'number'::value_type, 500, null, 'g',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 13, 'Spring onion, cut', 'পেঁয়াজ পাতা',
                false, true,
                'number'::value_type, 500, null, 'g',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 14, 'Broths ready', 'ঝোল',
                false, true,
                'number'::value_type, 2, null, 'types',
                true, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 14, 'Broths ready', 'ঝোল',
                false, true,
                'number'::value_type, 2, null, 'types',
                true, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'shift_lead'::user_role,
                    '{0,1,2,3,4,5,6}',
                    null,
                    null,
                    '17:00'::time, 30);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Bar Stock Readiness  (4 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Bar Stock Readiness' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Bar Stock Readiness', 'বার স্টক প্রস্তুতি', 'Section B of the Mise-en-place sheet.',
               'daily'::frequency, 'opening'::day_part, 1
          from sop_categories c where c.key = 'inventory'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Club soda', 'ক্লাব সোডা',
                false, true,
                'number'::value_type, 12, null, 'bottles',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Club soda', 'ক্লাব সোডা',
                false, true,
                'number'::value_type, 12, null, 'bottles',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 2, 'Sugar syrup', 'চিনির সিরাপ',
                false, true,
                'number'::value_type, 2, null, 'L',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 2, 'Sugar syrup', 'চিনির সিরাপ',
                false, true,
                'number'::value_type, 2, null, 'L',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 3, 'Lemon', 'লেবু',
                false, true,
                'number'::value_type, 30, null, 'pcs',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 3, 'Lemon', 'লেবু',
                false, true,
                'number'::value_type, 30, null, 'pcs',
                false, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 4, 'Ice', 'বরফ',
                false, true,
                'number'::value_type, 10, null, 'kg',
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 4, 'Ice', 'বরফ',
                false, true,
                'number'::value_type, 10, null, 'kg',
                false, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'staff'::user_role,
                    '{0,1,2,3,4,5,6}',
                    null,
                    null,
                    '17:00'::time, 30);
        end loop;
    end if;
end
$seed$;

-- ======================================================================
-- Food Safety Daily  (6 items)
-- ======================================================================
do $seed$
declare
    v_template_id uuid;
    v_item_id     uuid;
    v_outlet      record;
begin
    select id into v_template_id from checklist_templates
     where name = 'Food Safety Daily' and deleted_at is null;

    if v_template_id is null then
        insert into checklist_templates
            (category_id, name, name_bn, description, frequency, day_part, version)
        select c.id, 'Food Safety Daily', 'দৈনিক খাদ্য নিরাপত্তা', 'Not from AKIRA''s paper. Temperature bands are industry defaults - correct them to what the equipment actually holds.',
               'daily'::frequency, 'mid'::day_part, 1
          from sop_categories c where c.key = 'food_safety'
        returning id into v_template_id;

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 1, 'Broth hot-holding temperature', 'ঝোলের গরম রাখার তাপমাত্রা',
                false, true,
                'temperature_c'::value_type, 75, 95, '°C',
                true, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 1, 'Broth hot-holding temperature', 'ঝোলের গরম রাখার তাপমাত্রা',
                false, true,
                'temperature_c'::value_type, 75, 95, '°C',
                true, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 2, 'Walk-in fridge temperature', 'ওয়াক-ইন ফ্রিজের তাপমাত্রা',
                false, true,
                'temperature_c'::value_type, 0, 5, '°C',
                true, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 2, 'Walk-in fridge temperature', 'ওয়াক-ইন ফ্রিজের তাপমাত্রা',
                false, true,
                'temperature_c'::value_type, 0, 5, '°C',
                true, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 3, 'Chiller cold-holding temperature', 'চিলারের তাপমাত্রা',
                false, true,
                'temperature_c'::value_type, 0, 5, '°C',
                true, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 3, 'Chiller cold-holding temperature', 'চিলারের তাপমাত্রা',
                false, true,
                'temperature_c'::value_type, 0, 5, '°C',
                true, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 4, 'Freezer temperature', 'ফ্রিজারের তাপমাত্রা',
                false, true,
                'temperature_c'::value_type, -18, -15, '°C',
                true, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 4, 'Freezer temperature', 'ফ্রিজারের তাপমাত্রা',
                false, true,
                'temperature_c'::value_type, -18, -15, '°C',
                true, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 5, 'Staff grooming & handwash check', 'কর্মীদের পরিচ্ছন্নতা ও হাত ধোয়া পরীক্ষা',
                true, false,
                null::value_type, null, null, null,
                true, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 5, 'Staff grooming & handwash check', 'কর্মীদের পরিচ্ছন্নতা ও হাত ধোয়া পরীক্ষা',
                true, false,
                null::value_type, null, null, null,
                true, false, 'Seeded.');

        insert into checklist_template_items
            (template_id, sort_order, title, title_bn, requires_photo,
             requires_value, value_type, value_min, value_max, value_unit,
             is_critical, allow_na)
        values (v_template_id, 6, 'Allergen station separation', 'অ্যালার্জেন স্টেশন পৃথকীকরণ',
                true, false,
                null::value_type, null, null, null,
                false, false)
        returning id into v_item_id;

        -- Version 1 of this definition, so the run snapshot resolves.
        insert into checklist_template_item_versions
            (template_item_id, template_id, template_version, sort_order,
             title, title_bn, requires_photo, requires_value, value_type,
             value_min, value_max, value_unit, is_critical, allow_na, change_note)
        values (v_item_id, v_template_id, 1, 6, 'Allergen station separation', 'অ্যালার্জেন স্টেশন পৃথকীকরণ',
                true, false,
                null::value_type, null, null, null,
                false, false, 'Seeded.');

        -- Assign to every outlet that exists.
        for v_outlet in select id from outlets where deleted_at is null loop
            insert into checklist_assignments
                (template_id, outlet_id, assigned_role, active_weekdays,
                 interval_days, anchor_date, due_time_local, grace_minutes)
            values (v_template_id, v_outlet.id,
                    'shift_lead'::user_role,
                    '{0,1,2,3,4,5,6}',
                    null,
                    null,
                    '20:00'::time, 30);
        end loop;
    end if;
end
$seed$;

