-- -------------------------------------------------------------------------
-- 002 — Inventory catalogue
--
-- GENERATED by scripts/generate_inventory_seed.py — do not hand-edit.
-- Transcribed from AKIRA's paper count sheets (Aug 2026).
--
--   F&B Production - Hot Range          97 items
--   F&B Production - Desserts            9 items
--   Beverages / Bar Counter             13 items
--   F&B Service                         19 items
--   Housekeeping                        13 items
--   TOTAL                              151 items
--
-- Idempotent: re-running updates labels and leaves existing items alone.
-- -------------------------------------------------------------------------

-- Seeded catalogue belongs to the development organisation (0026).
insert into inventory_departments (organisation_id, key, label, label_bn, sort_order) values
    ('a1000000-0000-4000-8000-000000000002', 'fnb_hot_range', 'F&B Production - Hot Range', 'এফ অ্যান্ড বি প্রোডাকশন - হট রেঞ্জ', 10),
    ('a1000000-0000-4000-8000-000000000002', 'fnb_desserts', 'F&B Production - Desserts', 'এফ অ্যান্ড বি প্রোডাকশন - ডেজার্ট', 20),
    ('a1000000-0000-4000-8000-000000000002', 'beverages', 'Beverages / Bar Counter', 'পানীয় / বার কাউন্টার', 30),
    ('a1000000-0000-4000-8000-000000000002', 'fnb_service', 'F&B Service', 'এফ অ্যান্ড বি সার্ভিস', 40),
    ('a1000000-0000-4000-8000-000000000002', 'housekeeping', 'Housekeeping', 'হাউসকিপিং', 50)
on conflict (coalesce(organisation_id, '00000000-0000-0000-0000-000000000000'), key) do update set
    label = excluded.label,
    label_bn = excluded.label_bn,
    sort_order = excluded.sort_order;

insert into inventory_categories (organisation_id, key, label, label_bn, sort_order) values
    ('a1000000-0000-4000-8000-000000000002', 'vegetables', 'Vegetables', 'সবজি', 10),
    ('a1000000-0000-4000-8000-000000000002', 'fruits', 'Fruits', 'ফল', 15),
    ('a1000000-0000-4000-8000-000000000002', 'herbs', 'Herbs', 'ভেষজ', 20),
    ('a1000000-0000-4000-8000-000000000002', 'spices', 'Spices', 'মশলা', 30),
    ('a1000000-0000-4000-8000-000000000002', 'sauces', 'Sauces & Dressings', 'সস ও ড্রেসিং', 40),
    ('a1000000-0000-4000-8000-000000000002', 'oils', 'Oils', 'তেল', 50),
    ('a1000000-0000-4000-8000-000000000002', 'meat', 'Meat', 'মাংস', 60),
    ('a1000000-0000-4000-8000-000000000002', 'poultry', 'Poultry', 'হাঁস-মুরগি', 65),
    ('a1000000-0000-4000-8000-000000000002', 'dairy', 'Dairy', 'দুগ্ধজাত', 70),
    ('a1000000-0000-4000-8000-000000000002', 'rice', 'Rice', 'চাল', 80),
    ('a1000000-0000-4000-8000-000000000002', 'pulses', 'Pulses', 'ডাল', 85),
    ('a1000000-0000-4000-8000-000000000002', 'flour', 'Flour', 'আটা', 90),
    ('a1000000-0000-4000-8000-000000000002', 'prep', 'Prepared Components', 'প্রস্তুত উপকরণ', 100),
    ('a1000000-0000-4000-8000-000000000002', 'desserts', 'Dessert Ingredients', 'ডেজার্ট উপকরণ', 110),
    ('a1000000-0000-4000-8000-000000000002', 'beverage', 'Beverage', 'পানীয়', 120),
    ('a1000000-0000-4000-8000-000000000002', 'alcohol', 'Alcohol', 'অ্যালকোহল', 130),
    ('a1000000-0000-4000-8000-000000000002', 'sweetener', 'Sweeteners', 'মিষ্টিকারক', 140),
    ('a1000000-0000-4000-8000-000000000002', 'snacks', 'Snacks', 'স্ন্যাকস', 150),
    ('a1000000-0000-4000-8000-000000000002', 'dry_goods', 'Dry Goods', 'শুকনো সামগ্রী', 160),
    ('a1000000-0000-4000-8000-000000000002', 'packaging', 'Packaging', 'প্যাকেজিং', 170),
    ('a1000000-0000-4000-8000-000000000002', 'cleaning', 'Cleaning', 'পরিষ্কারক', 180),
    ('a1000000-0000-4000-8000-000000000002', 'uniform', 'Uniform', 'ইউনিফর্ম', 190)
on conflict (coalesce(organisation_id, '00000000-0000-0000-0000-000000000000'), key) do update set
    label = excluded.label,
    label_bn = excluded.label_bn,
    sort_order = excluded.sort_order;

-- Items are matched to their department and category by key, so this file
-- never hardcodes a uuid.
insert into inventory_items (organisation_id, name, name_bn, department_id, category_id, unit, notes)
select 'a1000000-0000-4000-8000-000000000002', v.name, v.name_bn, d.id, c.id, v.unit::inventory_unit, v.notes
from (values
    ('Garbage Bag', 'ময়লার ব্যাগ', 'housekeeping', 'cleaning', 'piece', null),
    ('16x20 Plastic Bag', '১৬x২০ প্লাস্টিকের ব্যাগ', 'housekeeping', 'packaging', 'piece', null),
    ('13x16 Plastic Bag', '১৩x১৬ প্লাস্টিকের ব্যাগ', 'housekeeping', 'packaging', 'piece', null),
    ('Cling Wrap', 'ক্লিং র‍্যাপ', 'housekeeping', 'packaging', 'roll', null),
    ('8x10 Ziplock Bag', '৮x১০ জিপলক ব্যাগ', 'housekeeping', 'packaging', 'piece', null),
    ('Detergent Powder', 'ডিটারজেন্ট পাউডার', 'housekeeping', 'cleaning', 'gram', null),
    ('Vim Bar', 'ভিম বার', 'housekeeping', 'cleaning', 'piece', null),
    ('Duster', 'ডাস্টার', 'housekeeping', 'cleaning', 'piece', null),
    ('Scotch Brite', 'স্কচ ব্রাইট', 'housekeeping', 'cleaning', 'piece', null),
    ('Steel Wool', 'স্টিল উল', 'housekeeping', 'cleaning', 'piece', null),
    ('Pillow', 'বালিশ', 'housekeeping', 'cleaning', 'piece', 'Listed under Cleaning on the source sheet, which looks wrong - confirm whether this is a scouring pad rather than a pillow.'),
    ('Sink Wiper', 'সিঙ্ক মোছার যন্ত্র', 'housekeeping', 'cleaning', 'piece', null),
    ('Sink Brush', 'সিঙ্ক ব্রাশ', 'housekeeping', 'cleaning', 'piece', null),
    ('Net Cap', 'নেট ক্যাপ', 'fnb_service', 'uniform', 'piece', null),
    ('Colin', 'কলিন', 'fnb_service', 'cleaning', 'millilitre', null),
    ('Floor Cleaner', 'মেঝে পরিষ্কারক', 'fnb_service', 'cleaning', 'millilitre', null),
    ('Harpic', 'হারপিক', 'fnb_service', 'cleaning', 'millilitre', null),
    ('Toilet Freshner', 'টয়লেট ফ্রেশনার', 'fnb_service', 'cleaning', 'piece', null),
    ('Room Freshner', 'রুম ফ্রেশনার', 'fnb_service', 'cleaning', 'piece', null),
    ('Table Wipe', 'টেবিল মোছা', 'fnb_service', 'cleaning', 'piece', null),
    ('Floor Brush', 'মেঝে ব্রাশ', 'fnb_service', 'cleaning', 'piece', null),
    ('Wiper', 'ওয়াইপার', 'fnb_service', 'cleaning', 'piece', null),
    ('Dry Mop', 'শুকনো মোছা', 'fnb_service', 'cleaning', 'piece', null),
    ('Mop', 'মপ', 'fnb_service', 'cleaning', 'piece', null),
    ('Chanachur', 'চানাচুর', 'fnb_service', 'snacks', 'gram', null),
    ('Gyoza & Yakitori Box', 'গিয়োজা এবং ইয়াকিতোরি বক্স', 'fnb_service', 'packaging', 'piece', null),
    ('Container 600ml', 'কন্টেইনার ৬০০ মিলি', 'fnb_service', 'packaging', 'piece', null),
    ('Container 1000ml', 'কন্টেইনার ১০০০ মিলি', 'fnb_service', 'packaging', 'piece', null),
    ('Guest Tissue / Napkin', 'অতিথির টিস্যু / ন্যাপকিন', 'fnb_service', 'packaging', 'packet', null),
    ('Wooden Skewers', 'কাঠের শলাকা', 'fnb_service', 'dry_goods', 'packet', null),
    ('Chopstick', 'চপস্টিক', 'fnb_service', 'dry_goods', 'packet', null),
    ('Water Jug', 'জলের জগ', 'fnb_service', 'dry_goods', 'jug', null),
    ('Mango Sticky Rice Mix', 'আমের আঠালো ভাতের মিশ্রণ', 'fnb_desserts', 'desserts', 'gram', null),
    ('Cream Cheese', 'ক্রিম চিজ', 'fnb_desserts', 'dairy', 'gram', null),
    ('Mango', 'আম', 'fnb_desserts', 'fruits', 'gram', null),
    ('Coconut Milk Powder', 'নারকেলের দুধের গুঁড়ো', 'fnb_desserts', 'dairy', 'gram', null),
    ('Dlecta Whipped Cream', 'ডলেকটা হুইপড ক্রিম', 'fnb_desserts', 'dairy', 'millilitre', null),
    ('MilkMaid', 'মিল্কমেইড', 'fnb_desserts', 'dairy', 'millilitre', null),
    ('Compound Chocolate', 'যৌগিক চকোলেট', 'fnb_desserts', 'desserts', 'gram', null),
    ('Gelatine Sheet', 'জেলাটিন শিট', 'fnb_desserts', 'desserts', 'piece', null),
    ('Baking Powder', 'বেকিং পাউডার', 'fnb_desserts', 'desserts', 'gram', null),
    ('Sake', 'সাকে', 'beverages', 'alcohol', 'millilitre', null),
    ('Club Soda', 'ক্লাব সোডা', 'beverages', 'beverage', 'bottle', 'Bar sheet listed this in ML, but it is counted and reordered by the bottle (750 ml each). Unit corrected to bottle so the par of 12 means 12 bottles rather than 12 ml.'),
    ('Coffee Syrup', 'কফি সিরাপ', 'beverages', 'beverage', 'millilitre', null),
    ('Grenadine', 'গ্রেনাডিন', 'beverages', 'beverage', 'millilitre', null),
    ('Litchi Slush', 'লিচু স্লাশ', 'beverages', 'beverage', 'millilitre', null),
    ('Sugar Syrup', 'চিনির সিরাপ', 'beverages', 'beverage', 'millilitre', null),
    ('Ice Cube', 'বরফ কিউব', 'beverages', 'beverage', 'kilogram', null),
    ('Instant Coffee Powder', 'ইনস্ট্যান্ট কফি পাউডার', 'beverages', 'beverage', 'gram', null),
    ('Lemon Juice', 'লেবুর রস', 'beverages', 'beverage', 'millilitre', null),
    ('Milk', 'দুধ', 'beverages', 'dairy', 'millilitre', null),
    ('Blue Pea Flower', 'নীল মটর ফুল', 'beverages', 'herbs', 'gram', null),
    ('Honey', 'মধু', 'beverages', 'sweetener', 'millilitre', null),
    ('Lemon', 'লেবু', 'beverages', 'vegetables', 'piece', null),
    ('Cucumber Brunoy Wedge', 'শসা ব্রুনয় ওয়েজ', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Sweet Corn', 'মিষ্টি ভুট্টা', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Celery', 'সেলারি', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Carrot', 'গাজর', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Ginger', 'আদা', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Potato', 'আলু', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Cabbage', 'বাঁধাকপি', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Bokchoy', 'বকচয়', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Shitake Mushroom', 'শিটাকে মাশরুম', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Button Mushroom', 'বাটন মাশরুম', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Tomato', 'টমেটো', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Peeled Garlic', 'খোসা ছাড়ানো রসুন', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Spring Onion', 'পেঁয়াজ পাতা', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Onion', 'পেঁয়াজ', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Pickle Ginger', 'আচার আদা', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Begun (Aubergine)', 'বেগুন', 'fnb_hot_range', 'vegetables', 'gram', 'Source sheet''s Bengali column read ''শুরু করা হয়েছে'' (= ''has been started''), a machine-translation error. Corrected to বেগুন.'),
    ('Karela', 'করলা', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Cucumber', 'শসা', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Ladies Finger', 'ঢেঁড়স', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Lau', 'লাউ', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Jhingey', 'ঝিঙে', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Potol', 'পটল', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Cauliflower', 'ফুলকপি', 'fnb_hot_range', 'vegetables', 'gram', null),
    ('Sugar', 'চিনি', 'fnb_hot_range', 'sweetener', 'gram', null),
    ('Chili Powder', 'মরিচের গুঁড়ো', 'fnb_hot_range', 'spices', 'gram', null),
    ('Black Pepper', 'গোলমরিচ', 'fnb_hot_range', 'spices', 'gram', null),
    ('Chilli Flakes', 'চিলি ফ্লেক্স', 'fnb_hot_range', 'spices', 'gram', null),
    ('Kashmiri Dry Chilli', 'কাশ্মীরি শুকনো মরিচ', 'fnb_hot_range', 'spices', 'gram', null),
    ('Dry Chilli', 'শুকনো মরিচ', 'fnb_hot_range', 'spices', 'gram', null),
    ('Green Chilli', 'কাঁচা মরিচ', 'fnb_hot_range', 'spices', 'gram', null),
    ('Whole Garam Masala', 'পুরো গরম মসলা', 'fnb_hot_range', 'spices', 'gram', null),
    ('Whole Panch Poron', 'পুরো পাঁচ ফোড়ন', 'fnb_hot_range', 'spices', 'gram', null),
    ('Five Spice Powder', 'পাঁচ মশলার গুঁড়ো', 'fnb_hot_range', 'spices', 'gram', null),
    ('Togarashi Powder', 'টগরশি পাউডার', 'fnb_hot_range', 'spices', 'gram', null),
    ('Clove', 'লবঙ্গ', 'fnb_hot_range', 'spices', 'gram', null),
    ('Elaichi', 'এলাচ', 'fnb_hot_range', 'spices', 'gram', null),
    ('Turmeric Powder', 'হলুদ গুঁড়ো', 'fnb_hot_range', 'spices', 'gram', null),
    ('Whole Corriander', 'পুরো ধনিয়া', 'fnb_hot_range', 'spices', 'gram', null),
    ('White Pepper', 'সাদা গোলমরিচ', 'fnb_hot_range', 'spices', 'gram', null),
    ('Black Sesame Seed', 'কালো তিল', 'fnb_hot_range', 'spices', 'gram', null),
    ('White Sesame Seed', 'সাদা তিলের বীজ', 'fnb_hot_range', 'spices', 'gram', null),
    ('Broth Powder', 'ঝোল পাউডার', 'fnb_hot_range', 'spices', 'gram', null),
    ('Ajino Moto', 'আজিনো মোটো', 'fnb_hot_range', 'spices', 'gram', null),
    ('Aromat Powder', 'অ্যারোমাট পাউডার', 'fnb_hot_range', 'spices', 'gram', null),
    ('Hondashi Powder', 'হোন্ডাশি পাউডার', 'fnb_hot_range', 'spices', 'gram', null),
    ('Salt', 'লবণ', 'fnb_hot_range', 'spices', 'gram', null),
    ('Miso Paste', 'মিসো পেস্ট', 'fnb_hot_range', 'prep', 'gram', null),
    ('Chili Paste', 'মরিচের পেস্ট', 'fnb_hot_range', 'sauces', 'gram', null),
    ('Tare', 'টারে', 'fnb_hot_range', 'sauces', 'gram', null),
    ('Chua Huh Chili Paste', 'চুয়া হুহ চিলি পেস্ট', 'fnb_hot_range', 'sauces', 'gram', null),
    ('Mayo', 'মায়ো', 'fnb_hot_range', 'sauces', 'gram', null),
    ('Vinegar', 'ভিনেগার', 'fnb_hot_range', 'sauces', 'millilitre', null),
    ('Dark Soy Sauce', 'ডার্ক সয়া সস', 'fnb_hot_range', 'sauces', 'millilitre', null),
    ('Light Soy Sauce', 'হালকা সয়া সস', 'fnb_hot_range', 'sauces', 'millilitre', null),
    ('Prawn Sauce Maker', 'চিংড়ি সস প্রস্তুতকারক', 'fnb_hot_range', 'sauces', 'gram', null),
    ('Oyster Sauce', 'অয়েস্টার সস', 'fnb_hot_range', 'sauces', 'millilitre', null),
    ('Mirin', 'মিরিন', 'fnb_hot_range', 'sauces', 'millilitre', null),
    ('Concentrate Vinegar', 'ঘন ভিনেগার', 'fnb_hot_range', 'sauces', 'millilitre', null),
    ('Sticky Sushi Rice', 'স্টিকি সুশি রাইস', 'fnb_hot_range', 'rice', 'gram', null),
    ('Staff Rice', 'স্টাফ রাইস', 'fnb_hot_range', 'rice', 'gram', null),
    ('Soyabean', 'সয়াবিন', 'fnb_hot_range', 'pulses', 'gram', null),
    ('Staff Dal', 'স্টাফ ডাল', 'fnb_hot_range', 'pulses', 'gram', null),
    ('Cream Cheese Mushroom Filling', 'ক্রিম চিজ মাশরুম ফিলিং', 'fnb_hot_range', 'prep', 'gram', null),
    ('Pork Gyoza Filling', 'পোর্ক গিয়োজা ফিলিং', 'fnb_hot_range', 'prep', 'gram', null),
    ('Chicken Gyoza Filling', 'চিকেন গিয়োজা ফিলিং', 'fnb_hot_range', 'prep', 'gram', null),
    ('Egg', 'ডিম', 'fnb_hot_range', 'poultry', 'piece', null),
    ('Aluminium Foil Roll', 'অ্যালুমিনিয়াম ফয়েল রোল', 'fnb_hot_range', 'packaging', 'roll', null),
    ('Sesame Oil', 'তিলের তেল', 'fnb_hot_range', 'oils', 'millilitre', null),
    ('Refined Oil', 'পরিশোধিত তেল', 'fnb_hot_range', 'oils', 'millilitre', null),
    ('Mustard Oil', 'সর্ষের তেল', 'fnb_hot_range', 'oils', 'millilitre', null),
    ('Truffle Oil', 'ট্রাফল তেল', 'fnb_hot_range', 'oils', 'millilitre', null),
    ('Chicken Sausage', 'মুরগির সসেজ', 'fnb_hot_range', 'meat', 'gram', null),
    ('Pork Keema', 'শুকরের কিমা', 'fnb_hot_range', 'meat', 'gram', null),
    ('Boiled Pork', 'সেদ্ধ শুকরের মাংস', 'fnb_hot_range', 'meat', 'gram', null),
    ('Chicken Bones', 'মুরগির হাড়', 'fnb_hot_range', 'meat', 'gram', null),
    ('Chicken Breast Boneless', 'হাড়বিহীন মুরগির বুকের মাংস', 'fnb_hot_range', 'meat', 'gram', null),
    ('Chicken Leg Boneless', 'হাড়বিহীন মুরগির রান', 'fnb_hot_range', 'meat', 'gram', null),
    ('Pork Belly', 'শুকরের পেটের মাংস', 'fnb_hot_range', 'meat', 'gram', null),
    ('Pork Fat', 'শূকরের চর্বি', 'fnb_hot_range', 'meat', 'gram', null),
    ('Chicken Claws', 'মুরগির নখ', 'fnb_hot_range', 'meat', 'gram', null),
    ('Chicken Fat', 'মুরগির চর্বি', 'fnb_hot_range', 'meat', 'gram', null),
    ('Mint', 'পুদিনা', 'fnb_hot_range', 'herbs', 'gram', null),
    ('Basil', 'তুলসী', 'fnb_hot_range', 'herbs', 'gram', null),
    ('Coriander', 'ধনিয়া', 'fnb_hot_range', 'herbs', 'gram', null),
    ('Bay Leaf', 'তেজপাতা', 'fnb_hot_range', 'herbs', 'gram', null),
    ('Maida Flour', 'ময়দা', 'fnb_hot_range', 'flour', 'gram', null),
    ('Tempura Flour', 'টেম্পুরা ফ্লাওয়ার', 'fnb_hot_range', 'flour', 'gram', null),
    ('Panko', 'পাংকো', 'fnb_hot_range', 'dry_goods', 'gram', 'Source sheet read ''Habit Panko'' with Bengali ''অভ্যাস'' (= ''habit''), a literal mistranslation. Recorded as Panko breadcrumbs - confirm.'),
    ('Gyoza Wrap', 'গিয়োজা র‍্যাপ', 'fnb_hot_range', 'dry_goods', 'piece', null),
    ('Nori Sheet', 'নোরি শীট', 'fnb_hot_range', 'dry_goods', 'piece', null),
    ('Puffed Rice', 'মুড়ি', 'fnb_hot_range', 'dry_goods', 'gram', null),
    ('Brown Garlic Butter', 'বাদামী রসুনের মাখন', 'fnb_hot_range', 'dairy', 'gram', null),
    ('Butter', 'মাখন', 'fnb_hot_range', 'dairy', 'gram', null),
    ('Blended Cheese', 'মিশ্রিত পনির', 'fnb_hot_range', 'dairy', 'gram', null),
    ('Paneer', 'পনির', 'fnb_hot_range', 'dairy', 'gram', null),
    ('White Chinese Cooking Wine', 'সাদা চীনা রান্নার ওয়াইন', 'fnb_hot_range', 'alcohol', 'millilitre', null),
    ('Cooking Wine', 'রান্নার ওয়াইন', 'fnb_hot_range', 'alcohol', 'millilitre', null)
) as v(name, name_bn, dept_key, cat_key, unit, notes)
join inventory_departments d on d.key = v.dept_key
left join inventory_categories c on c.key = v.cat_key
where not exists (
    select 1 from inventory_items existing
    where existing.department_id = d.id
      and lower(existing.name) = lower(v.name)
      and existing.deleted_at is null
);

-- Par levels, for every outlet that exists. Only the mise-en-place sheet
-- carries minimums, so most items start with no par level and an admin
-- sets them per outlet.
insert into inventory_outlet_levels (outlet_id, item_id, par_level, is_stocked)
select o.id, i.id, v.par_level, true
from (values
    ('Club Soda', 'beverages', 12::numeric),
    ('Sugar Syrup', 'beverages', 2000::numeric),
    ('Lemon', 'beverages', 30::numeric),
    ('Ice Cube', 'beverages', 10::numeric),
    ('Egg', 'fnb_hot_range', 30::numeric),
    ('Spring Onion', 'fnb_hot_range', 500::numeric)
) as v(name, dept_key, par_level)
join inventory_departments d on d.key = v.dept_key
join inventory_items i on i.department_id = d.id and lower(i.name) = lower(v.name)
cross join outlets o
where o.deleted_at is null
on conflict (outlet_id, item_id) do nothing;

